import { useState } from 'react'
import HudCard from '../HudCard.jsx'
import StatusBadge from '../StatusBadge.jsx'
import { aarReport, mission } from '../../data/mockData.js'

const SEV_COLOR = { Critical: 'var(--red)', High: 'var(--amber)', Medium: 'var(--cyan)', Low: 'var(--muted)' }

function buildReportMarkdown() {
  return [
    `# AFTER-ACTION REPORT — ${mission.title}`,
    `\n> PREVIEW // MOCK — fictional scenario, generated by Ghost Command: ReconOPS demo\n`,
    `## Objective\n${mission.objective}\n`,
    `## Statistics\n${aarReport.stats.map((s) => `- ${s.label}: ${s.value}`).join('\n')}\n`,
    `## Timeline\n${aarReport.timeline.map((t) => `- **${t.t}** [${t.sev}] ${t.label}`).join('\n')}\n`,
    `## Findings\n${aarReport.findings}\n`,
    `## Lessons Learned\n${aarReport.lessons}\n`,
    `## Recommendation\n${aarReport.recommendation}\n`,
  ].join('\n')
}

export default function DebriefView() {
  const [generated, setGenerated] = useState(false)
  const [thinking, setThinking] = useState(false)

  const generate = () => {
    setThinking(true)
    setTimeout(() => { setThinking(false); setGenerated(true) }, 1600)
  }

  const exportReport = () => {
    const blob = new Blob([buildReportMarkdown()], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'AAR-quiet-horizon.md'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <HudCard
      panelId="workspace"
      className="workspace"
      title="Operation Debrief · After-Action Synthesis"
      right={<StatusBadge status="Complete" pulse />}
    >
      <div className="view-layout">
        <div className="view-main">
          <div className="view-controls">
            <button className="btn-green" onClick={generate}>◈ Generate AAR</button>
            <button className="btn-amber" onClick={exportReport} disabled={!generated} style={!generated ? { opacity: 0.45 } : undefined}>
              ⇩ Export Report (.md)
            </button>
          </div>

          <div className="diag-stats" style={{ gridTemplateColumns: 'repeat(4, 1fr)' }}>
            {aarReport.stats.map((s) => (
              <div key={s.label} className="diag-stat">
                <div className="val">{s.value}</div>
                <div className="lbl">{s.label}</div>
              </div>
            ))}
          </div>

          <div className="mini-title" style={{ marginTop: 6 }}>OPERATION TIMELINE</div>
          <div style={{ overflowY: 'auto', minHeight: 0 }}>
            {aarReport.timeline.map((t, i) => (
              <div key={i} className="transcript-line">
                <span className="tt" style={{ minWidth: 44 }}>{t.t}</span>
                <span className="spk" style={{ color: SEV_COLOR[t.sev], minWidth: 60 }}>{t.sev}</span>
                <span className="txt">{t.label}</span>
              </div>
            ))}
          </div>

          {thinking && <div className="thinking">LLM SYNTHESIZING FULL-OPERATION ARCHIVE <i /><i /><i /></div>}
          {generated && (
            <div style={{ overflowY: 'auto' }}>
              <div className="brief-section"><div className="bs-label">Findings</div><div className="bs-text">{aarReport.findings}</div></div>
              <div className="brief-section"><div className="bs-label">Lessons Learned</div><div className="bs-text" style={{ color: 'var(--amber)' }}>{aarReport.lessons}</div></div>
              <div className="brief-section"><div className="bs-label">Recommendation</div><div className="bs-text" style={{ color: 'var(--cyan)' }}>{aarReport.recommendation}</div></div>
            </div>
          )}
        </div>

        <aside className="view-side">
          <div>
            <div className="mini-title">OUTCOME <StatusBadge status="Complete" /></div>
            <div className="kv"><span className="k">Mission</span><span className="v">{mission.title}</span></div>
            <div className="kv"><span className="k">Result</span><span className="v" style={{ color: 'var(--green)' }}>Objective met</span></div>
            <div className="kv"><span className="k">Escalation</span><span className="v">None</span></div>
            <div className="kv"><span className="k">Assets Lost</span><span className="v">0 (1 degraded)</span></div>
          </div>
          <div>
            <div className="mini-title">ARCHIVE STATUS</div>
            {['Video archives sealed', 'Audio + transcripts stored', 'Track fusion snapshot saved', 'Documents cross-indexed', 'Decision log notarized'].map((s, i) => (
              <div key={i} className="phase-row st-Complete">
                <span className="ph-dot" style={{ background: 'var(--green)', borderColor: 'var(--green)' }} />
                <span style={{ flex: 1 }}>{s}</span>
              </div>
            ))}
          </div>
          <div>
            <div className="mini-title">NEXT CYCLE</div>
            <div className="ai-text">This AAR becomes training context for the next operation: the plan template, sensor placement lessons, and anomaly signatures are fed back into the planning layer.</div>
          </div>
        </aside>
      </div>
    </HudCard>
  )
}
